Add possibility to modify the debug level
metis-vela-unipd/sailtrack-module pull request #16
Opened 2024-03-22 09:48 UTC by Luca-Gale

Proposed solution for [issue #15](https://github.com/metisvela/sailtrack-module/issues/15)

2024-03-22 20:00 UTC, matteocarnelos requested changes
Thanks for the work! However, I think we still need some changes to get this merged. I left some comments in the code.

2024-03-22 20:00 UTC, matteocarnelos commented on README.md
> + - `SAILTRACK_MODULE_LOG_LEVEL` (ARDUHAL_LOG_LEVEL_*): Log level control (NONE, ERROR, WARN, INFO, DEBUG, TRACE). Default to INFO.
It would be nice to make the flag consistent with the others:
```suggestion
 - `STM_LOG_LEVEL` (ARDUHAL_LOG_LEVEL_*): Log level control (NONE, ERROR, WARN, INFO, DEBUG, TRACE). Defaults to INFO.
```

2024-03-22 20:00 UTC, matteocarnelos commented on include/SailtrackModule.h
> +
According to previous comment:
```suggestion
#ifndef STM_LOG_LEVEL
#define CORE_DEBUG_LEVEL ARDUHAL_LOG_LEVEL_INFO
#else
#define CORE_DEBUG_LEVEL STM_LOG_LEVEL
#endif

```

2024-03-22 20:00 UTC, matteocarnelos commented on include/SailtrackModule.h
> +    static int subscribe(const char *topic);
Was this format done on purpose? If not, I think it's better to revert these changes to keep the code style consistent with the rest of the code.

2024-03-22 20:00 UTC, matteocarnelos commented on platformio.ini
> -    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
This flag was set to make it possible to see the `log_i()` calls inside of the SimpleCounter example. By removing the flag we disable those logs. Consider reverting it.

2024-03-23 14:54 UTC, Luca-Gale commented on platformio.ini
> -    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
Doesn't the flag automatically default to INFO if STM_LOG_INFO is not defined?

2024-03-24 20:00 UTC, matteocarnelos commented on platformio.ini
> -    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
It does it for the SailtrackModule library only. Here we want to enable the `log_i()` calls in the SimpleCounter example. To test this, you can run the example without the flag set and see if the info logs are printed.

2024-03-27 22:37 UTC, matteocarnelos requested changes
Some last nitpicks and we are ready to merge!

2024-03-27 22:37 UTC, matteocarnelos commented on library.json
> +}
Always remember to add an empty line at the end of files ([reason](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file)). You can configure VSCode to do that automatically by checking the settings _Files: Insert Final Newline_ and _Files: Trim Final Newlines_.
```suggestion
}

```

2024-03-27 22:37 UTC, matteocarnelos commented on platformio.ini
> +    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
Same as above.
```suggestion
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO

```

2024-03-28 23:00 UTC, matteocarnelos approved these changes
And we are good to go!

2024-04-12 16:29 UTC, merged